### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
I'll land this after the previous PR – they overlap

**Comment by nshahan** [comment]
What is the Travis sanity check?

**Comment by nshahan** [comment]
Is it just that it can survive a dartfmt and the analyzer?

**Comment by kevmoo** [comment]
> Is it just that it can survive a dartfmt and the analyzer?

Yup.

**Comment by nshahan** [comment]
OK cool. I just wanted to make sure this wasn't intended to run the sanity_check.dart but wasn't.

**Pull request merged**
