### PR TITLE
Removed deprecated calls to JSON

### PR DESCRIPTION
**Pull request by dineshbhosale**
Removed deprecated calls to `JSON.decode` and `JSON.encode`

### CODE REVIEW

**Comment by nshahan** [comment]
jsonDecode and jsonEncode are not found. Are they from another library?

@kevmoo?

**Comment by dineshbhosale** [comment]
It's in `dart:convert`

**Comment by nshahan** [comment]
Ahh ok. I see. This will have to wait until we have the latest SDK available in all of our environments.

**Comment by dineshbhosale** [comment]
Ok, I get messages in dart analysis to replace this.

**Comment by kevmoo** [comment]
@dineshbhosale – yup. It's still there, just deprecated.

We're going to clean these up internally later in one big update.

Thanks for your help!

**Pull request closed without merging**
