### PR TITLE
pin the analyzer version due to breakage

### PR DESCRIPTION
**Pull request by jakemac53**
looks like alpha.2 is causing some issues, we can investigate this after dartconf

cc @kevmoo this fixes the issue you were talking about

cc @matanlurey @alorenzen

### CODE REVIEW

**Comment by chalin** [comment]
> cc @kevmoo this fixes the issue you were talking about

What was the issue?

**Comment by nshahan** [comment]
I haven't been able to repro the issue. Curious what  either. I'm not opposed to pinning the version but it has been working with alpha+2 for ~2 months. I'd like to know where the actual problem is coming from.

**Comment by jakemac53** [comment]
I was getting an error on pub upgrade (without --no-precompile) when running the angular template compiler.

I can't repro it any longer either.... which is pretty bizarre. I am going to close this as I don't think analyzer was actually the issue.

**Comment by chalin** [comment]
(I'm glad that I'm not the only one seeing intermittent behavior.)

**Pull request closed without merging**
