### PR TITLE
update `disabled` attributes to assign to the property

### PR DESCRIPTION
**Pull request by jakemac53**
I don't know that much about angular, but I think this is the correct solution? The generated template is otherwise trying to assign the empty string to the disabled field which is a boolean.

### CODE REVIEW

**Comment by nshahan** [comment]
Were you observing an error that this fixes?

**Comment by jakemac53** [comment]
When trying to compile with dartdevc I get:

```
[error] A value of type 'String' can't be assigned to a variable of type 'bool'. (package:angular2_components_example/app_component.template.dart, line 7897, col 49)

Please fix all errors before compiling (warnings are okay).
```

**Comment by jakemac53** [comment]
Nevermind, looks like this is a bleeding edge strong mode issue

**Comment by nshahan** [comment]
Ok to delete the branch?

**Pull request closed without merging**
